### ISSUE TITLE
Success Screens (July 3 Milestones)

### ISSUE THREAD

**Issue by jamesinnyc** [XXIX/pronoun-tracker#19]
- [ ]You’ve created a book!
- [ ]You’ve published your book!
- [ ]Your book got its first sale! (Maybe. Easier to do it in an email)
- [ ]Best week of sales yet! (Maybe. Easier to do it in an email)
I wish this screen was more of a celebration. What if the blue paper came to an end (maybe even with a visual indication that it's the bottom of a sheet, not just a line), and the background were white (we filled it out, and now we're in space). Maybe when you land on it, we can throw some confetti to celebrate.
Marking this as complete and adding this comment to the later milestone in a future sprint
